# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb6c963f9a90b2413c09e317d19f0b50e5347c09ec477ba3e27bb3b5d32b91cbcb057adba237ad99554baf0752340891148795cc49a82e9817b130fcafedb203

test:
  secret_key_base: 4c445ab8b453b1ec0ac6a14bf02d3ebbbe590356872bc5d98e5284324ead03ab96e1271191bd78b108bb5e85161523e04770f8fe6991e6a7cae7bb873630b8d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
